# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 09:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('about_me', models.TextField()),
                ('rank', models.IntegerField(blank=True, default=0, editable=False)),
                ('voted', models.IntegerField(blank=True, default=0, editable=False)),
                ('answers', models.IntegerField(blank=True, default=0, editable=False)),
                ('questions', models.IntegerField(blank=True, default=0, editable=False)),
                ('is_use_gravatar', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar_url', models.URLField(blank=True, default='http://www.gravatar.com/avatar/', null=True)),
                ('website', models.URLField(blank=True, default='http://', null=True)),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/forum/avatars/')),
                ('content_md', models.TextField(blank=True, editable=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
